"""Thư viện ví dụ mẫu. Tách riêng để sau này dùng lại cho chức năng tạo bài tập tự động."""
from __future__ import annotations

EXAMPLES = [
    {"id": "para-line-bounds", "category": "Parabol và đường thẳng",
     "title": "Parabol và đường thẳng, cho cận",
     "description": "Đường thẳng cắt parabol ngay trong đoạn [-3; 1], miền chia làm hai khoảng.",
     "f1": "x^2", "f2": "2*x+3/2", "a": "-3", "b": "1", "mode": "manual"},
    {"id": "para-line-auto", "category": "Parabol và đường thẳng",
     "title": "Parabol và đường thẳng, tự tìm giao điểm",
     "description": "Diện tích giới hạn bởi y = x² và y = x + 2.",
     "f1": "x^2", "f2": "x+2", "a": "", "b": "", "mode": "auto"},
    {"id": "two-parabolas", "category": "Hai parabol",
     "title": "Hai parabol cắt nhau",
     "description": "y = x² và y = 4 − x²: giao điểm là số vô tỉ.",
     "f1": "x^2", "f2": "4-x^2", "a": "", "b": "", "mode": "auto"},
    {"id": "ox-parabola", "category": "Hàm số và trục Ox",
     "title": "Parabol và trục Ox",
     "description": "y = x² − 4 và y = 0; giao điểm với Ox là hai cận.",
     "f1": "x^2-4", "f2": "0", "a": "", "b": "", "mode": "auto"},
    {"id": "cubic-line", "category": "Nhiều giao điểm",
     "title": "Hàm bậc ba và đường thẳng",
     "description": "y = x³ − 3x và y = x có ba giao điểm nên miền chia làm hai phần.",
     "f1": "x^3-3*x", "f2": "x", "a": "", "b": "", "mode": "auto"},
    {"id": "sin-ox", "category": "Hàm lượng giác",
     "title": "Một chu kỳ của sin x",
     "description": "y = sin x và trục Ox trên [0; 2π]: hai phần đối dấu, diện tích lấy giá trị tuyệt đối.",
     "f1": "sin(x)", "f2": "0", "a": "0", "b": "2*pi", "mode": "manual"},
    {"id": "sin-cos", "category": "Hàm lượng giác",
     "title": "sin x và cos x",
     "description": "Hai đồ thị cắt nhau tại x = π/4 trong đoạn [0; π].",
     "f1": "sin(x)", "f2": "cos(x)", "a": "0", "b": "pi", "mode": "manual"},
    {"id": "exp-line", "category": "Hàm mũ",
     "title": "eˣ và đường thẳng (nghiệm gần đúng)",
     "description": "Phương trình eˣ = x + 2 không giải được bằng công thức đóng, hệ thống dùng nghiệm số.",
     "f1": "exp(x)", "f2": "x+2", "a": "", "b": "", "mode": "auto"},
    {"id": "log-ox", "category": "Hàm mũ",
     "title": "Logarit tự nhiên",
     "description": "Diện tích dưới y = 1/x từ 1 đến e bằng 1.",
     "f1": "1/x", "f2": "0", "a": "1", "b": "e", "mode": "manual"},
    {"id": "sqrt-line", "category": "Hàm căn",
     "title": "Căn thức và đường thẳng",
     "description": "y = √x và y = x/2 cắt nhau tại x = 0 và x = 4.",
     "f1": "sqrt(x)", "f2": "x/2", "a": "", "b": "", "mode": "auto"},
    {"id": "half-disk", "category": "Hàm căn",
     "title": "Nửa hình tròn",
     "description": "y = √(4 − x²) và trục Ox: diện tích nửa hình tròn bán kính 2.",
     "f1": "sqrt(4-x^2)", "f2": "0", "a": "", "b": "", "mode": "auto"},
]
